server:
  port: 8081
  servlet:
    session:
      cookie:
        name: CLIENT1_SESSION
spring:
  security:
    saml2:
      relyingparty:
        registration:
          keycloak:
            entity-id: client1-saml
            assertingparty:
              entity-id: http://localhost:8080/realms/sso-realm-a
              metadata-uri: http://localhost:8080/realms/sso-realm-a/protocol/saml/descriptor
              singlesignon:
                sign-request: false
logging:
  level:
    org.springframework.security: DEBUG
